# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  encoding: utf8
  database: project_development
  pool: 5
  timeout: 5000
  username:
  password:

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: project_test
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: pg
  encoding: utf8
  database: project_production
  pool: 5
  timeout: 5000
  username:
  password:

cucumber:
  <<: *TEST
  
default: &default
  adapter: pg
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  
on_worker_boot do:
  # Valid on Rails 4.1+ using the `config/database.yml` method of setting `pool` size
  ActiveRecord::Base.establish_connection